apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskrunner
  template:
    metadata:
      labels:
        app: taskrunner
    spec:
      containers:
        - name: taskrunner
          image: taskrunner-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo:27017/kaiburrdb"
---
apiVersion: v1
kind: Service
metadata:
  name: taskrunner-service
spec:
  type: NodePort
  selector:
    app: taskrunner
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
